envVarGroups:
  - name: spree-envs
    envVars:
      - key: DB_POOL
        value: 10

databases:
  - name: spree-db
    databaseName: spree_production
    user: spree_user
    plan: starter

services:
  - type: web
    name: spree-web
    runtime: ruby
    plan: standard
    buildCommand: bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    releaseCommand: bundle exec rails db:create || true && bundle exec rails db:migrate && bundle exec rails db:seed
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spree-db
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: keyvalue
          property: connectionString

  - type: worker
    name: spree-worker
    runtime: ruby
    plan: standard
    buildCommand: bin/render-build.sh
    startCommand: bundle exec sidekiq
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spree-db
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: keyvalue
          property: connectionString
      - key: REDIS_CACHE_URL
        fromService:
          type: keyvalue
          name: keyvalue-cache
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production

  - type: keyvalue
    name: keyvalue
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: noeviction

  - type: keyvalue
    name: keyvalue-cache
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: allkeys-lru
