envVarGroups:
  - name: spree-envs
    envVars:
      - key: DB_POOL
        value: 10

# Remove the databases section since you're using Railway
# databases:
#   - name: spree-db
#     databaseName: spree
#     user: spree
#     plan: basic-1gb
#     diskSizeGB: 10

services:
  - type: web
    name: spree-web
    runtime: ruby
    plan: standard
    buildCommand: bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      # - key: DATABASE_URL
      #   value: your_railway_mysql_connection_string_here
      - key: SECRET_KEY_BASE
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: keyvalue
          property: connectionString

  - type: worker
    name: spree-worker
    runtime: ruby
    plan: standard
    buildCommand: bin/render-build.sh
    startCommand: bundle exec sidekiq
    envVars:
      - key: DATABASE_URL
        value: your_railway_mysql_connection_string_here
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: keyvalue
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: REDIS_CACHE_URL
        fromService:
          type: keyvalue
          name: keyvalue-cache
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
  
  - type: keyvalue
    name: keyvalue
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: noeviction

  - type: keyvalue
    name: keyvalue-cache
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: allkeys-lru