# PostgreSQL settings
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aa_enterprise_development
  username: postgres
  password: password
  host: localhost

test:
  <<: *default
  database: aa_enterprise_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
